version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      - "POSTGRES_USER=postgres"
      # - "POSTGRES_PASSWORD=password"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    command: bundle exec rails s puma
    volumes:
      - ../Celebrity:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
  bundle: