default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: celebrity_development
  template: template0

production:
  <<: *default
  database: celebrity_development
  username: postgres
  password:

test:
  <<: *default
  database: celebrity_test
