source 'https://rubygems.org'

gem 'rails', '~> 5.0.3'
gem 'carrierwave',             '1.1.0'#画像アップロード用追加
gem 'mini_magick',             '4.7.0'#画像アップロード用追加
gem 'bcrypt',   '3.1.11'
gem 'faker'
gem 'roo'# Excelファイルを参照するため
gem 'spreadsheet'# 既存Excelファイルを参照するため
gem 'pg', '~> 0.18'
gem 'bootstrap-sass', '3.3.7'
gem 'puma',         '3.9.1'
gem 'sass-rails',   '5.0.6'
gem 'uglifier',     '3.2.0'
gem 'coffee-rails', '4.2.2'
gem 'jquery-rails', '4.3.1'
# gem 'jquery-turbolinks'
# gem 'turbolinks',   '5.0.1'
gem 'jbuilder',     '2.6.1'
gem 'bootstrap_form'
gem 'kaminari'
# gem 'kaminari-bootstrap', '~> 3.0.1'
gem "paranoia", '~> 2.2'
gem 'jquery-ui-rails'
gem 'whenever', :require => false
gem 'slack-api'


group :development, :test do
  gem 'byebug',  '9.0.6', platform: :mri
  gem 'pry-rails' #pry-rails を入れるとshow-modelsのコマンドが Rails consoleで使えるようになる
end

group :development do
  gem 'web-console',           '3.5.1'
  gem 'listen',                '3.0.8'
  gem 'spring',                '2.0.2'
  gem 'spring-watcher-listen', '2.0.1'
end

group :test do
  gem 'rails-controller-testing', '1.0.2'
  gem 'minitest-reporters',       '1.1.14'
  gem 'guard',                    '2.13.0'
  gem 'guard-minitest',           '2.4.4'
end

group :production do
  gem 'pg', '~> 0.18'
  gem 'therubyracer'
end
 
# Windows環境ではtzinfo-dataというgemを含める必要があります
gem 'tzinfo-data', platforms: [:ruby, :mingw, :mswin, :x64_mingw, :jruby]